### ISSUE TITLE
Integration does not work with Ha 2025.6

### ISSUE THREAD

**Issue by OliverGreenforest** [RubenHarms/ha-harvia-xenio-wifi#16]
Since latest core update integration stopped working. 

Here's the protocol: 

Logger: homeassistant.config_entries
Quelle: config_entries.py:749
Erstmals aufgetreten: 08:15:47 (3 Vorkommnisse)
Zuletzt protokolliert: 08:20:07

Error setting up entry Harvia Sauna for harvia_sauna
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/harvia_sauna/__init__.py", line 631, in async_setup_entry
    hass.async_create_task(  hass.config_entries.async_forward_entry_setup(entry, entity_type) )
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by RubenHarms** [comment]
Problem has been resolved, please update to the new version!

**Comment by OliverGreenforest** [comment]
World perfectly. Thanks a lot!
